export const useMockTracks = () => {
  const tracks: ITrack[] = [
    {
      id: 1,
      name: 'Break My Soul',
      artworkUrl: 'https://source.unsplash.com/collection/31/1600x1600',
      artistName: 'Beyonce',
      audioUrl: '/static/sample1.mp3',
      genre: ['Soul'],
    },
    {
      id: 2,
      name: 'Alone',
      artworkUrl: 'https://source.unsplash.com/collection/32/1600x1600',
      artistName: 'Rod Wave',
      audioUrl: '/static/sample2.mp3',
      genre: ['Pop'],
    },
    {
      id: 3,
      name: 'Twilight',
      artworkUrl: 'https://source.unsplash.com/collection/33/1600x1600',
      artistName: 'John Cha',
      audioUrl: '/static/sample3.mp3',
      genre: ['Jazz'],
    },
    {
      id: 4,
      name: 'Cause We`ve Ended As Lovers',
      artworkUrl: 'https://source.unsplash.com/collection/34/1600x1600',
      artistName: 'jeff beck',
      audioUrl: '/static/sample1.mp3',
      genre: ['Jazz'],
    },
    {
      id: 5,
      name: 'I`m Buzzed',
      artworkUrl: 'https://source.unsplash.com/collection/35/1600x1600',
      artistName: 'Michael Landau',
      audioUrl: '/static/sample1.mp3',
      genre: ['Blues'],
    },
    {
      id: 6,
      name: 'slow blues',
      artworkUrl: 'https://source.unsplash.com/collection/36/1600x1600',
      artistName: 'Michael Landau',
      audioUrl: '/static/sample1.mp3',
      genre: ['Blues'],
    },
    {
      id: 7,
      name: 'Worried Life Blues',
      artworkUrl: 'https://source.unsplash.com/collection/37/1600x1600',
      artistName: 'Michael Landau',
      audioUrl: '/static/sample1.mp3',
      genre: ['Blues'],
    },
    {
      id: 8,
      name: 'Judy',
      artworkUrl: 'https://source.unsplash.com/collection/38/1600x1600',
      artistName: 'Michael Landau',
      audioUrl: '/static/sample1.mp3',
      genre: ['Blues'],
    },
    {
      id: 9,
      name: 'Judy',
      artworkUrl: 'https://source.unsplash.com/collection/39/1600x1600',
      artistName: 'Michael Landau',
      audioUrl: '/static/sample1.mp3',
      genre: ['Blues'],
    },
    {
      id: 10,
      name: 'Judy',
      artworkUrl: 'https://source.unsplash.com/collection/40/1600x1600',
      artistName: 'Michael Landau',
      audioUrl: '/static/sample1.mp3',
      genre: ['Blues'],
    },
  ];
  return tracks;
};
