export const useMockTracks = () => {
  const tracks: ITrack[] = [
    {
      id: 1,
      name: 'Break My Soul',
      artworkUrl: 'https://source.unsplash.com/collection/1/1600x1600',
      artistName: 'Beyonce',
      audioUrl: '',
      genre: ['Soul'],
    },
    {
      id: 2,
      name: 'Alone',
      artworkUrl: 'https://source.unsplash.com/collection/2/1600x1600',
      artistName: 'Rod Wave',
      audioUrl: '',
      genre: ['Pop'],
    },
    {
      id: 3,
      name: 'Twilight',
      artworkUrl: 'https://source.unsplash.com/collection/3/1600x1600',
      artistName: 'John Cha',
      audioUrl: '',
      genre: ['Jazz'],
    },
    {
      id: 4,
      name: 'Cause We`ve Ended As Lovers',
      artworkUrl: 'https://source.unsplash.com/collection/4/1600x1600',
      artistName: 'jeff beck',
      audioUrl: '',
      genre: ['Jazz'],
    },
    {
      id: 5,
      name: 'I`m Buzzed',
      artworkUrl: 'https://source.unsplash.com/collection/5/1600x1600',
      artistName: 'Michael Landau',
      audioUrl: '',
      genre: ['Blues'],
    },
    {
      id: 6,
      name: 'slow blues',
      artworkUrl: 'https://source.unsplash.com/collection/6/1600x1600',
      artistName: 'Michael Landau',
      audioUrl: '',
      genre: ['Blues'],
    },
    {
      id: 7,
      name: 'Worried Life Blues',
      artworkUrl: 'https://source.unsplash.com/collection/7/1600x1600',
      artistName: 'Michael Landau',
      audioUrl: '',
      genre: ['Blues'],
    },
    {
      id: 8,
      name: 'Judy',
      artworkUrl: 'https://source.unsplash.com/collection/8/1600x1600',
      artistName: 'Michael Landau',
      audioUrl: '',
      genre: ['Blues'],
    },
    {
      id: 9,
      name: 'Judy',
      artworkUrl: 'https://source.unsplash.com/collection/9/1600x1600',
      artistName: 'Michael Landau',
      audioUrl: '',
      genre: ['Blues'],
    },
    {
      id: 10,
      name: 'Judy',
      artworkUrl: 'https://source.unsplash.com/collection/10/1600x1600',
      artistName: 'Michael Landau',
      audioUrl: '',
      genre: ['Blues'],
    },
  ];
  return tracks;
};
